import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF005DB6),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFD6E3FF),
  onPrimaryContainer: Color(0xFF001B3D),
  secondary: Color(0xFF9C432E),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFFFDAD2),
  onSecondaryContainer: Color(0xFF3D0700),
  tertiary: Color(0xFF6F5675),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFF9D8FE),
  onTertiaryContainer: Color(0xFF28132F),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFDFBFF),
  onBackground: Color(0xFF1A1B1E),
  surface: Color(0xFFFDFBFF),
  onSurface: Color(0xFF1A1B1E),
  surfaceVariant: Color(0xFFE0E2EC),
  onSurfaceVariant: Color(0xFF43474E),
  outline: Color(0xFF74777F),
  onInverseSurface: Color(0xFFF1F0F4),
  inverseSurface: Color(0xFF2F3033),
  inversePrimary: Color(0xFFA9C7FF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF005DB6),
);
